config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :body, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: 'jason',
                               password: 'password',
                               except: %i[index show]

  def index
    @articles = Article.all.order(id: :desc)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update (article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: 'jason',
                               password: 'password',
                               only: :destroy

  def new
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)

    if @comment.save
      redirect_to article_path(@article)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: 303
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.erb
<div class="article">
  <p>
    <%= article.title %>
  </p>
  <%= link_to 'View', article %>
</div>

app/views/articles/_form.html.erb
<div class="card">
  <%= form_with model: article do |form| %>
    <div>
      <p>
        <%= form.label :title %>
      </p>
      <%= form.text_field :title %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div class="error">
          <%= message %>
        </div>
      <% end %>
    </div>
    <div class="spacing"></div>
    <div>
      <p>
        <%= form.label :body %>
      </p>
      <%= form.text_area :body %>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div class="error">
          <%= message %>
        </div>
      <% end %>
    </div>
    <div class="spacing"></div>
    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="back">
  <span class="material-icons">keyboard_arrow_left</span>
  <%= link_to 'Back', article_path(@article) %>
</div>
<div class="header-container">
  <div class="header">Edit Article</div>
  <div class="subtext">Update an existing article</div>
</div>
<%= render 'form', article: @article %>
<div class="spacing"></div>

app/views/articles/index.html.erb
<div class="header-container">
  <div class="header">Articles</div>
  <div class="subtext">
    <% if @articles.length == 1 %>
      <%= "#{@articles.length} article" %>
    <% else %>
      <%= "#{@articles.length} articles" %>
    <% end %>
  </div>
  <button><%= link_to 'New Article', new_article_path %></button>
</div>
<div class="articles">
  <div class="articles-label">
    <p>Article Title</p>
  </div>
  <%= render @articles %>
</div>
<div class="spacing"></div>

app/views/articles/new.html.erb
<div class="back">
  <span class="material-icons">keyboard_arrow_left</span>
  <%= link_to 'Back', articles_path %>
</div>
<div class="header-container">
  <div class="header">New Article</div>
  <div class="subtext">Create a new article</div>
</div>
<%= render 'form', article: @article %>
<div class="spacing"></div>

app/views/articles/show.html.erb
<div class="back">
  <span class="material-icons">keyboard_arrow_left</span>
  <%= link_to 'Back', articles_path %>
</div>
<div class="card">
  <div class="header-container">
    <div class="header">
      <%= @article.title %>
    </div>
    <div class="subtext">
      <span><%= @article.created_at.in_time_zone(8).strftime("%B %d, %Y") %></span>
      <span><%= @article.created_at.in_time_zone(8).strftime("%I:%M %p") %></span>
    </div>
  </div>
  <div class="article-body">
    <pre><%= @article.body %></pre>
  </div>
  <div class="show-footer">
    <span class="edit"><%= link_to 'Edit', edit_article_path(@article) %></span>
    <span class="delete">
      <%= link_to "Delete", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
    </span>
  </div>
</div>
<div class="spacing"></div>
<div class="comments">
  <div class="card">
    <div class="header-container">
      <div class="header">Comments</div>
      <div class="subtext">
        <% if @article.comments.length == 1 %>
          <%= "#{@article.comments.length} comment" %>
        <% else %>
          <%= "#{@article.comments.length} comments" %>
        <% end %>
      </div>
      <button><%= link_to 'New Comment', new_article_comment_path(@article) %></button>
    </div>
    <%= render @article.comments %>
  </div>
</div>
<div class="spacing"></div>

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="profile"></div>
  <div>
    <div class="name"><%= comment.commenter %></div>
    <div class="comment-body">
      <%= comment.body %>
    </div>
  </div>
  <div class="delete">
    <%= link_to "Delete", [comment.article, comment],
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
  </div>
</div>

app/views/comments/_form.html.erb
 <%= form_with model: [article, comment] do |form| %>
  <div>
    <p>
      <%= form.label :commenter %>
    </p>
    <%= form.text_field :commenter %>
    <% comment.errors.full_messages_for(:commenter).each do |message| %>
      <div class="error">
        <%= message %>
      </div>
    <% end %>
  </div>
  <div class="spacing"></div>
  <div>
    <p>
      <%= form.label :body %>
    </p>
    <%= form.text_area :body %>
    <% comment.errors.full_messages_for(:body).each do |message| %>
      <div class="error">
        <%= message %>
      </div>
    <% end %>
  </div>
  <div class="spacing"></div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/new.html.erb
<div class="back">
  <span class="material-icons">keyboard_arrow_left</span>
  <%= link_to 'Back', article_path(@article) %>
</div>
<div class="comments">
  <div class="card">
    <div class="header-container">
      <div class="header">Add comment</div>
      <div class="subtext">Create a new comment</div>
    </div>
    <%= render 'form', article: @article, comment: @comment %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="navleft">
    <%= link_to 'blog.', root_path %>
  </div>
  <div class="navright">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('logo.svg') %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="body">
      <div class="content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>